--[[ <HCExtension>
@name			Ad-Blocker
@author			truefriend-cz / internet sources
@version		1.1
@description	Script for filtering domains and URL words (must use with truefriend-cz script pack only) - Extension list position priority: 2
@license		CC BY-NC-SA (Attribution-NonCommercial-ShareAlike - https://creativecommons.org/licenses/by-nc-sa/)
@event 			RequestHeaderReceived
</HCExtension> ]]

function RequestHeaderReceived()

	whitelist = {'googleusercontent.com'}
	blacklist = {'adcash', 'trafficflux', '007-gateway.com', 'admedia.com', 'affiliationcash.com', 'bstrtb.com', 'deplayer.net', 'futureresiduals.com', 'iunbrudy.net', 'milabra.com', 'performanceadvertising.mobi', 'saltamendors.com', 'tldadserv.com', 'wigetstudios.com',
				'juicyads.com', 'vivastreet.co.uk', '0icep80f.com', 'ad-media.org', 'affiliation-france.com', 'btnibbler.com', 'deployads.com', 'futureus.com', 'ivism.org', 'millennialmedia.com', 'performance-based.com', 'salvador24.com', 'tlvmedia.com', 'winbuyer.com',
				'traffichunt.com', 'trafficstars.com', 'adxpansion.com', 'tynt.com', '101m3.com', 'admedias.net', 'affiliationworld.com', 'btrll.com', 'derlatas.com', 'fwmrm.net', 'iwantmoar.net', 'millionairesurveys.com', 'performancetrack.info', 'saple.net', 'tnyzin.ru', 'wingads.com',
				'103092804.com', 'admedo.com', 'affiliationzone.com', 'bttbgroup.com', 'destinationurl.com', 'fxdepo.com', 'ixnp.com', 'minimumpay.info', 'performancingads.com', 'sascdn.com', 'toboads.com', 'winsspeeder.info',
				'10fbb07a4b0.se', 'admeld.com', 'affilijack.de', 'bu520.com', 'detroposal.com', 'fxyc0dwa.com', 'izeads.com', 'mirago.com', 'permutive.com', 'satgreera.com', 'tokenads.com', 'wlmarketing.com',
				'10pipsaffiliates.com', 'admeta.com', 'affiliproducts.com', 'bubblesmedia.ru', 'deuskex.link', 'g05.info', 'j2ef76da3.website', 'mirrorpersonalinjury.co.uk', 'persevered.com', 'saveads.net', 'tollfreeforwarding.com', 'wmmediacorp.com',
				'1100i.com', 'admission.net', 'affiliserve.com', 'bucketsofbanners.com', 'developermedia.com', 'g4whisperermedia.com', 'jadcenter.com', 'miva.com', 'pexu.com', 'saveads.org', 'tomekas.com', 'wonclick.com',
				'123date.me', 'admitad.com', 'affimo.de', 'budgetedbauer.com', 'deximedia.com', 'gagacon.com', 'jango.com', 'mixmarket.biz', 'pezrphjl.com', 'sayadcoltd.com', 'tonefuse.com', 'wonderlandads.com',
				'123vidz.com', 'admixer.net', 'affinitad.com', 'budurl.com', 'dexplatform.com', 'gagenez.com', 'jangonetwork.com', 'mixpo.com', 'pgmediaserve.com', 'saymedia.com', 'tool-site.com', 'wootmedia.net',
				'152media.com', 'admngronline.com', 'affinity.com', 'buhafr.net', 'dgmatix.com', 'gainmoneyfast.com', 'jaspensar.com', 'mkhoj.com', 'pgpartner.com', 'sba.about.co.kr', 'top26.net', 'wopdi.com',
				'15f3c01a.info', 'admob.com', 'affiz.net', 'buildtrafficx.com', 'dgmaustralia.com', 'galleyn.com', 'jbrlsr.com', 'mktmobi.com', 'pgssl.com', 'sbaffiliates.com', 'topauto10.com', 'wordbankads.com',
				'15f3c01c.info', 'admpads.com', 'affplanet.com', 'bulletproofserving.com', 'dgmaxinteractive.com', 'gambling-affiliation.com', 'jdoqocy.com', 'mktseek.com', 'pharmcash.com', 'sbcpower.com', 'topcasino10.com', 'wordego.com',
				'174.142.194.177', 'admtpmp127.com', 'afftrack.com', 'bunchofads.com', 'dhundora.com', 'gameads.com', 'jdproject.net', 'mlnadvertising.com', 'pheedo.com', 'scanmedios.com', 'topdi.net', 'worlddatinghere.com',
				'17a898b9.info', 'admulti.com', 'aflrm.com', 'bunny-net.com', 'diamondtraff.com', 'game-advertising-online.com', 'jdrm4.com', 'mmadsgadget.com', 'philbardre.com', 'scanscout.com', 'topeuro.biz', 'worldrewardcenter.net',
				'17a898bb.info', 'admzn.com', 'africawin.com', 'burbanked.info', 'dianomioffers.co.uk', 'gamecetera.com', 'jdtracker.com', 'mmgads.com', 'philipstreehouse.info', 'sceno.ru', 'topfox.co.uk', 'worthathousandwords.com',
				'188server.com', 'adne.tv', 'afterdownload.com', 'burjam.com', 'digipathmedia.com', 'game-clicks.com', 'jeetyetmedia.com', 'mmismm.com', 'philosophere.com', 'scootloor.com', 'tophotoffers.com', 'worthyadvertising.com',
				'18clicks.com', 'adnectar.com', 'afterdownloads.com', 'burnsoftware.info', 'digitrevenue.com', 'gamehotus.com', 'jellr.net', 'mmngte.net', 'phonespybubble.com', 'scratchaffs.com', 'topshelftraffic.com', 'wuarnurf.net',
				'194.71.107.25', 'adnet.biz', 'afy11.net', 'burstnet.com', 'dilpy.org', 'gamersad.com', 'jemmgroup.com', 'mmondi.com', 'pianobuyerdeals.com', 'search123.uk.com', 'torads.me', 'wuatriser.net',
				'1clickdownloads.com', 'adnet.com', 'agcdn.com', 'businesscare.com', 'dinclinx.com', 'gamersbanner.com', 'jiwire.com', 'mmotraffic.com', 'picadmedia.com', 'seccoads.com', 'torconpro.com', 'wudr.net',
				'1e0y.xyz', 'adnet.de', 'agentcenters.com', 'businessclick.com', 'dipads.net', 'gamesbannerexchange.com', 'jizzontoy.com', 'moatads.com', 'picbucks.com', 'secondstreetmedia.com', 'torerolumiere.net', 'wulium.com',
				'1phads.com', 'adnet.lt', 'aggregateknowledge.com', 'busterzaster.de', 'directaclick.com', 'gamesrevenue.com', 'jmp9.com', 'mobatori.com', 'picsti.com', 'secureintl.com', 'toroadvertising.com', 'wurea.com',
				'1sadx.net', 'adnet.ru', 'aglocobanners.com', 'buxflow.com', 'directile.info', 'gandrad.org', 'jo7cofh3.com', 'mobatory.com', 'pictela.net', 'securesoft.info', 'toroadvertisingmedia.com', 'wwbn.com',
				'1yk851od.com', 'adnet.vn', 'agmtrk.com', 'buxp.org', 'directile.net', 'ganja.com', 'jobsyndicate.com', 'mobday.com', 'pikkr.net', 'secure-softwaremanager.com', 'torrida.net', 'wwv4ez0n.com',
				'206ads.com', 'adnet-media.net', 'agvzvwof.com', 'buxx.mobi', 'directleads.com', 'gannett.gcion.com', 'jobtarget.com', 'mobgold.com', 'pinballpublishernetwork.com', 'securewebsiteaccess.com', 'torrpedoads.net', 'wwwadcntr.com',
				'20dollars2surf.com', 'adnetworkme.com', 'aim4media.com', 'buyflood.com', 'directoral.info', 'garristo.com', 'joytocash.com', 'mobicont.com', 'pioneeringad.com', 'securitain.com', 'totaladperformance.com', 'wwwpromoter.com',
				'213.163.70.183', 'adnext.fr', 'aimatch.com', 'buyorselltnhomes.com', 'directorym.com', 'garvmedia.com', 'jque.net', 'mobifobi.com', 'pipaoffers.com', 'sedoparking.com', 'total-media.net', 'wzus1.ask.com',
				'247realmedia.com', 'adngin.com', 'airpush.com', 'buysellads.com', 'directrev.com', 'gate-ru.com', 'js.cdn.ac', 'mobikano.com', 'piticlik.com', 'seductionprofits.com', 'totalprofitplan.com', 'x.mochiads.com',
				'254a.com', 'adnimation.com', 'ajansreklam.net', 'buzzcity.net', 'directtrack.com', 'gatikus.com', 'jscount.com', 'mobile-10.com', 'pivotalmedialabs.com', 'seekads.net', 'totemcash.com', 'x4300tiz.com',
				'2d4c3870.info', 'adnium.com', 'alchemysocial.com', 'buzzparadise.com', 'directtrk.com', 'gayadnetwork.com', 'jsfeedadsget.com', 'mobileraffles.com', 'pivotrunner.com', 'sekindo.com', 'totrack.ru', 'xad.com',
				'2d4c3872.info', 'adnoble.com', 'alfynetwork.com', 'bwinpartypartners.com', 'dispop.com', 'g-cash.biz', 'jsretra.com', 'mobiright.com', 'pixazza.com', 'selectr.net', 'tower-colocation.de', 'xadcentral.com',
				'2dpt.com', 'adnow.com', 'alimama.com', 'byspot.com', 'distantnews.com', 'geede.info', 'jssearch.net', 'mobisla.com', 'pixeltrack66.com', 'sellhealth.com', 'tower-colocation.info', 'xcelltech.com',
				'2mdn.info', 'adnxs.com', 'allabc.com', 'byzoo.org', 'distantstat.com', 'geek2us.net', 'jtrakk.com', 'mobitracker.info', 'pixfuture.net', 'selsin.net', 'tpnads.com', 'xcelsiusadserver.com',
				'2mdn.net', 'adnxs.net', 'alleliteads.com', 'bzrvwbsh5o.com', 'districtm.ca', 'gefhasio.com', 'judicated.com', 'mobiyield.com', 'pixxur.com', 'sendptp.com', 'tqlkg.com', 'xchangebanners.com',
				'2xbpub.com', 'adnxs1.com', 'allianrd.net', 'c8.net.ua', 'dl-rms.com', 'geld-internet-verdienen.net', 'juiceadv.com', 'mobizme.net', 'pjatr.com', 'senzapudore.it', 'tqlkg.net', 'xclicks.net',
				'30daychange.co', 'adocean.pl', 'allmt.com', 'c8factor.com', 'dmg-mobile.com', 'gemineering.com', 'juiceadv.net', 'moborobot.com', 'pjtra.com', 'senzapudore.net', 'traceadmanager.com', 'xcrsqg.com',
				'32b4oilo.com', 'adohana.com', 'alloydigital.com', 'callhelpmetaroll.rocks', 'dmu20vut.com', 'genericlink.com', 'jujuads.com', 'mobpartner.mobi', 'platinumadvertisement.com', 'serialbay.com', 'trackadvertising.net', 'xdev.info',
				'32d1d3b9c.se', 'adonion.com', 'allslotscasino.com', 'camleyads.info', 'dntrck.com', 'genericsteps.com', 'jujzh9va.com', 'mobstrks.com', 'play24.us', 'seriousfiles.com', 'trackcorner.com', 'xeontopa.com',
				'3393.com', 'adonly.com', 'allyes.com', 'campanja.com', 'dojerena.com', 'genesismedia.com', 'jumboaffiliates.com', 'mobtrks.com', 'playertraffic.com', 'servali.net', 'tracki112.com', 'xfs5yhr1.com',
				'350media.com', 'adonweb.ru', 'alphabird.com', 'canoeklix.com', 'dollarade.com', 'genovesetacet.com', 'jumbolt.ru', 'mobytrks.com', 'pleeko.com', 'servebom.com', 'tracking.to', 'xgraph.net',
				'360ads.com', 'adoperator.com', 'alphabirdnetwork.com', 'capacitygrid.com', 'dollarsponsor.com', 'geo-idm.fr', 'jumpelead.com', 'mocean.mobi', 'plenomedia.com', 'servedbyadbutler.com', 'tracking101.com', 'xjfjx8hw.com',
				'360adshost.net', 'adoptim.com', 'alphagodaddy.com', 'capitatmarket.com', 'domainadvertising.com', 'geoipads.com', 'jumptap.com', 'modelegating.com', 'plexop.net', 'servedbyopenx.com', 'tracking11.com', 'xmasdom.com',
				'360adstrack.com', 'adorika.com', 'alpinedrct.com', 'captainad.com', 'domainbuyingservices.com', 'geopromos.com', 'junbi-tracker.com', 'moffsets.com', 'pllddc.com', 'servemeads.com', 'trackingoffer.info', 'xmlconfig.ltassrv.com',
				'360installer.com', 'adorika.net', 'alternads.info', 'captifymedia.com', 'domainsponsor.com', 'geovisite.com', 'jursp.com', 'mogointeractive.com', 'plocap.com', 'serve-sys.com', 'trackingoffer.net', 'xplrer.co',
				'360popads.com', 'adotic.com', 'alternativeadverts.com', 'carambo.la', 'domdex.com', 'gestionpub.com', 'juruasikr.net', 'mojiva.com', 'plugerr.com', 'serving-sys.com', 'trackpath.biz', 'xs.mochiads.com',
				'360yield.com', 'adotomy.com', 'altitude-arena.com', 'carbonads.com', 'domri.net', 'getgamers.eu', 'justrelevant.com', 'mojoaffiliates.com', 'plusfind.net', 'sethads.info', 'trackpromotion.net', 'xtcie.com',
				'365sbaffiliates.com', 'adotube.com', 'am10.ru', 'careerjournalonline.com', 'doogleonduty.com', 'getgscfree.com', 'jusukrs.com', 'mokonocdn.com', 'plxserve.com', 'sev4ifmxa.com', 'trackstarsengland.net', 'xtendadvert.com',
				'3cnce854.com', 'adpacks.com', 'am11.ru', 'carrier.bz', 'dorenga.com', 'getscorecash.com', 'jwaavsze.com', 'money4ads.com', 'pmsrvr.com', 'sevenads.net', 'trackthatad.com', 'xtendmedia.com',
				'3lift.com', 'adparlor.com', 'am15.net', 'cartorkins.com', 'dotandad.com', 'getthislistbuildingvideo.biz', 'jyvtidkx.com', 'moneycosmos.com', 'pnoss.com', 'sevendaystart.com', 'tracktor.co.uk', 'xubob.com',
				'3lr67y45.com', 'adpath.mobi', 'amazon-adsystem.com', 'casalemedia.com', 'dotomi.com', 'gettipsz.info', 'k0z09okc.com', 'money-cpm.fr', 'pntra.com', 'sexitnow.com', 'trackword.net', 'xvika.com',
				'3omb.com', 'adpay.com', 'amazon-cornerstone.com', 'cash4members.com', 'double.net', 'gghfncd.net', 'kanoodle.com', 'moneytec.com', 'pntrac.com', 'sexmoney.com', 'trackyourlinks.com', 'xx00.info',
				'3rdads.com', 'adperfect.com', 'amazonily.com', 'cashatgsc.com', 'doubleclick.com', 'ggncpm.com', 'kantarmedia.com', 'moneywhisper.com', 'pntrs.com', 'shakamech.com', 'tradeexpert.net', 'xxlink.net',
				'3redlightfix.com', 'adperium.com', 'am-display.com', 'cash-duck.com', 'doubleclick.net', 'giantaffiliates.com', 'kavanga.ru', 'monkeybroker.net', 'pointclicktrack.com', 'shareasale.com', 'tradepopups.com', 'xylopologyn.com',
				'3t7euflv.com', 'adphreak.com', 'amertazy.com', 'cashmylinks.com', 'doubleclicks.me', 'gib-gib-la.com', 'keewurd.com', 'monsoonads.com', 'pointroll.com', 'sharegods.com', 'traff-advertazer.com', 'ya88s1yk.com',
				'43plc.com', 'adpinion.com', 'amgdgt.com', 'cashonvisit.com', 'doublemax.net', 'gigamega.su', 'kehalim.com', 'mookie1.com', 'points2shop.com', 'shareresults.com', 'traffboost.net', 'yabuka.com',
				'46.165.197.153^', 'adpionier.de', 'amobee.com', 'cashtrafic.com', 'doublepimp.com', 'gimiclub.com', 'kerg.net', 'mootermedia.com', 'polawrg.com', 'share-server.com', 'trafficbarads.com', 'yadomedia.com',
				'46.165.197.231^', 'adplans.info', 'ampxchange.com', 'cashtrafic.info', 'doublerads.com', 'gklmedia.com', 'ketoo.com', 'mooxar.com', 'polluxnetwork.com', 'sharethrough.com', 'trafficbroker.com', 'yambotan.ru',
				'4affiliate.net', 'adplex.media', 'anastasiasaffiliate.com', 'cashworld.biz', 'doublerecall.com', 'glical.com', 'keywordblocks.com', 'moregamers.com', 'polmontventures.com', 'shoogloonetwork.com', 'trafficfactory.biz', 'yardr.net',
				'4dsply.com', 'adplxmd.com', 'andohs.net', 'casino.betsson.com', 'doubleverify.com', 'globaladsales.com', 'kikuzip.com', 'moreplayerz.com', 'polyad.net', 'shopalyst.com', 'trafficforce.com', 'yawnedgtuis.org',
				'4e43ac9c.info', 'adppv.com', 'andomedia.com', 'casiours.com', 'down1oads.com', 'globaladv.net', 'kinley.com', 'morgdm.ru', 'polydarth.com', 'shoppingads.com', 'traffichaus.com', 'yb0t.com',
				'4uvjosuc.com', 'adpredictive.com', 'andomediagroup.com', 'caspion.com', 'downloadboutique.com', 'globalinteractive.com', 'kintokup.com', 'moselats.com', 'popads.net', 'shopzyapp.com', 'trafficjunky.net', 'ycasmd.info',
				'4wnet.com', 'adpremo.com', 'anet*.tradedoubler.com', 'casterpretic.com', 'downloadthesefile.com', 'globalsuccessclub.com', 'kioshow.com', 'movad.net', 'popadscdn.net', 'showyoursite.com', 'trafficmasterz.net', 'yceml.net',
				'50.7.243.123', 'adprofit2share.com', 'angege.com', 'castplatform.com', 'downsonglyrics.com', 'global-success-club.net', 'kiosked.com', 'mpnrs.com', 'popcash.net', 'siamzone.com', 'trafficmp.com', 'yeabble.com',
				'5362367e.info', 'adproper.info', 'annualinternetsurvey.com', 'caygh.com', 'dp25.kr', 'globaltakeoff.net', 'kitnmedia.com', 'mpression.net', 'popcpm.com', 'silence-ads.com', 'trafficrevenue.net', 'yesadsrv.com',
				'5clickcashsoftware.com', 'adprotected.com', 'anomiely.com', 'cbaazars.com', 'dpbolvw.net', 'glowdot.com', 'kjgh5o.com', 'mprezchc.com', 'popcpv.com', 'silstavo.com', 'trafficspaces.net', 'yes-messenger.com',
				'5dimes.com', 'adprovi.de', 'anonymousads.com', 'cbclickbank.com', 'dpmsrv.com', 'gmads.net', 'klikadvertising.com', 'msads.net', 'popearn.com', 'silverads.net', 'traffic-supremacy.com', 'yesnexus.com',
				'5gl1x9qc.com', 'adprs.net', 'anrdoezrs.net', 'cbclicks.com', 'dpsrexor.com', 'go2jump.org', 'kliksaya.com', 'mtagmonetizationa.com', 'popmajor.com', 'simpio.com', 'trafficswarm.com', 'yieldads.com',
				'600z.com', 'adquest3d.com', 'answered-questions.com', 'cb-content.com', 'dpstack.com', 'go2media.org', 'klikvip.com', 'mtagmonetizationb.com', 'popmarker.com', 'simpleinternetupdate.com', 'trafficsway.com', 'yieldadvert.com',
				'63.225.61.4', 'adready.com', 'anwufkjjja.com', 'cbleads.com', 'draugonda.net', 'go2speed.org', 'klipmart.com', 'mtrcss.com', 'popmyad.com', 'simply.com', 'trafficsynergy.com', 'yieldbuild.com',
				'64.20.60.123', 'adreadytractions.com', 'anymedia.lv', 'cbn.tbn.ru', 'dreamaquarium.com', 'godspeaks.net', 'klixfeed.com', 'mujap.com', 'popmyads.com', 'simplyhired.com', 'traffictrader.net', 'yieldkit.com',
				'74.117.182.77^', 'adresellers.com', 'anyxp.com', 'cc-dt.com', 'dreamsearch.or.kr', 'goember.com', 'kloapers.com', 'multiadserv.com', 'poponclick.com', 'simusangr.com', 'trafficular.com', 'yieldlab.net',
				'777seo.com', 'adrevolver.com', 'aoqneyvmaz.com', 'cdn.mobicow.com', 'drfflt.info', 'gofindmedia.net', 'klonedaset.org', 'munically.com', 'popsads.com', 'singlesexdates.com', 'trafficvance.com', 'yieldmanager.com',
				'78.138.126.253', 'adrich.cash', 'aorms.com', 'cdna.tremormedia.com', 'drowle.com', 'gogoplexer.com', 'knorex.asia', 'music-desktop.com', 'popshow.info', 'sitebrand.com', 'trafficwave.net', 'yieldmanager.net',
				'78.140.131.214^', 'adrise.de', 'aorpum.com', 'cdnads.com', 'dsero.net', 'gojoingscnow.com', 'knowd.com', 'mutary.com', 'poptarts.me', 'siteencore.com', 'trafficz.com', 'yieldmo.com',
				'7insight.com', 'adrocket.com', 'apex-ad.com', 'cdn-image.com', 'dsnextgen.com', 'goodadvert.ru', 'kolition.com', 'mxtads.com', 'popularitish.com', 'sitescout.com', 'trafficzap.com', 'yieldoptimizer.com',
				'7search.com', 'ads.sexier.com', 'apmebf.com', 'cdnrl.com', 'dsnr-affiliates.com', 'goodadvertising.info', 'komoona.com', 'myaffiliates.com', 'popularmedia.net', 'sitescoutadserver.com', 'traffirms.com', 'yieldselect.com',
				'7u8a8i88.com', 'ads01.com', 'appads.com', 'cdnservr.com', 'dsultra.com', 'googleadservicepixel.com', 'kontextua.com', 'myclickbankads.com', 'populis.com', 'sitesense-oo.com', 'trahic.ru', 'yieldtraffic.com',
				'82d914.se', 'ads2ads.net', 'appendad.com', 'centralnervous.net', 'dtmpub.com', 'googlesyndicatiion.com', 'koocash.com', 'mycooliframe.net', 'populisengage.com', 'sitethree.com', 'trapasol.com', 'yieldx.com',
				'83nsdjqqo1cau183xz.com', 'ads2srv.com', 'applebarq.com', 'cerotop.com', 'dtzads.com', 'googletagservices.com/tag/js/gpt_', 'korrelate.net', 'mydreamads.com', 'popunder.ru', 'sittiad.com', 'traveladvertising.com', 'yldbt.com',
				'888casino.com', 'ads4cheap.com', 'apportium.com', 'cgecwm.org', 'duactinor.net', 'googletagservices.com/tag/static/', 'kovla.com', 'myemailbox.info', 'popundertotal.com', 'skimlinks.com', 'travelscream.com', 'yldmgrimg.net',
				'888games.com', 'ads-4u.com', 'appr8.net', 'chango.com', 'dualmarket.info', 'gopjn.com', 'kqzyfj.com', 'myinfotopia.com', 'popunderz.com', 'skinected.com', 'travidia.com', 'yllix.com',
				'888media.net', 'adsafeprotected.com', 'apptap.com', 'chanished.net', 'dudelsa.com', 'gorgonkil.com', 'kr3vinsx.com', 'my-layer.net', 'popuptraffic.com', 'skoovyads.com', 'tredirect.com', 'ymads.com',
				'888medianetwork.com', 'adsalvo.com', 'april29-disp-download.com', 'chansiar.net', 'duetads.com', 'gotoplaymillion.com', 'kromeleta.ru', 'mylinkbox.com', 'popupvia.com', 'skyactivate.com', 'trenpyle.com', 'yobr.net',
				'888poker.com', 'adsame.com', 'apsmediaagency.com', 'charltonmedia.com', 'duggiads.com', 'gourmetads.com', 'kuad.kusogi.com', 'mynewcarquote.us', 'pornv.org', 'skyscrpr.com', 'triadmedianetwork.com', 'yoc-adserver.com',
				'888promos.com', 'adsbookie.com', 'apxlv.com', 'checkm8.com', 'dumedia.ru', 'governmenttrainingexchange.com', 'kuangard.net', 'myplayerhd.net', 'posternel.com', 'slikslik.com', 'tribalfusion.com', 'yodr.net',
				'8yxupue8.com', 'adsbrook.com', 'ar.voicefive.com', 'checkmystats.com.au', 'durnowar.com', 'goviral.hs.llnwd.net', 'kumpulblogger.com', 'mysearch-online.com', 'postrelease.com', 'slimspots.com', 'trigami.com', 'yomri.net',
				'97d73lsi.com', 'adscale.de', 'arab4eg.com', 'checkoutfree.com', 'durokuro.com', 'goviral-content.com', 'l3op.info', 'mythings.com', 'poweradvertising.co.uk', 'slimtrade.com', 'trk4.com', 'yopdi.com',
				'9d63c80da.pw', 'adscampaign.net', 'arabweb.biz', 'cherytso.com', 'durtz.com', 'gpacalculatorhighschoolfree.com', 'ladbrokesaffiliates.com.au', 'myuniques.ru', 'powerfulbusiness.net', 'slinse.com', 'trkalot.com', 'yottacash.com',
				'9newstoday.net', 'adscendmedia.com', 'arcadebannerexchange.net', 'chicbuy.info', 'dutolats.net', 'grabmyads.com', 'lakequincy.com', 'myvads.com', 'powerlinks.com', 'smaato.net', 'trkclk.net', 'youcandoitwithroi.com',
				'9ts3tpia.com', 'adsclickingnetwork.com', 'arcadebannerexchange.org', 'chinagrad.ru', 'dvaminusodin.net', 'grabo.bg', 'lakidar.net', 'mz28ismn.com', 'ppcindo.com', 'smaclick.com', 'trker.com', 'youlamedia.com',
				'a.adroll.com', 'adsdk.com', 'arcadebanners.com', 'china-netwave.com', 'dyino.com', 'grafpedia.com', 'landsraad.cc', 'n388hkxg.com', 'ppclinking.com', 'smart.allocine.fr', 'trklnks.com', 'youlouk.com',
				'a.raasnet.com', 'adsdot.ph', 'arcadebe.com', 'chipleader.com', 'dynamicoxygen.com', 'grapeshot.co.uk', 'lanistaconcepts.com', 'nabbr.com', 'ppctrck.com', 'smart2.allocine.fr', 'trks.us', 'youradexchange.com',
				'a2dfp.net', 'ads-elsevier.net', 'arcadechain.com', 'chitika.com', 'dynamitedata.com', 'gratisnetwork.com', 'largestable.com', 'nagrande.com', 'ppcwebspy.com', 'smartad.ee', 'trllxv.co', 'yourfastpaydayloans.com',
				'a2pub.com', 'adsensecamp.com', 'areasnap.com', 'chitika.net', 'e9mlrvy1.com', 'greatbranddeals.com', 'laserhairremovalstore.com', 'nanigans.com', 'ppsearcher.ru', 'smartadserver.com', 'trndi.net', 'yourquickads.com',
				'a3pub.com', 'adserv8.com', 'artbr.net', 'chiuawa.net', 'eads.to', 'greenads.org', 'launchbit.com', 'nativead.co', 'precisionclick.com', 'smartdevicemedia.com', 'trtrccl.com', 'your-tornado-file.com',
				'a433.com', 'adserve.com', 'arti-mediagroup.com', 'chronicads.com', 'eads-adserving.com', 'greenlabelppc.com', 'layer-ad.org', 'nativeads.com', 'predictad.com', 'smarterdownloads.net', 'truex.com', 'your-tornado-file.org',
				'a4dtrk.com', 'adserve.ph', 'as5000.com', 'chualangry.com', 'earnify.com', 'grenstia.com', 'layerloop.com', 'nbjmp.com', 'prestadsng.com', 'smart-feed-online.com', 'trw12.com', 'ypppdc.com',
				'a5pub.com', 'ad-server.co.za', 'asafesite.com', 'cibleclick.com', 'easyad.com', 'gretzalz.com', 'layerwelt.com', 'nbstatic.com', 'prexista.com', 'smarttargetting.co.uk', 'trygen.co.uk', 'ypprr.com',
				'aa.voice2page.com', 'adserver-fx.com', 'aseadnet.com', 'city-ads.de', 'easy-adserver.com', 'greystripe.com', 'lazynerd.info', 'ncrjsserver.com', 'prf.hn', 'smarttargetting.com', 'ttzmedia.com', 'yrrrbn.me',
				'aaa.at4.info', 'ad-serverparc.nl', 'asklots.com', 'citysite.net', 'easydownload4you.com', 'gripdownload.co', 'lbm1.com', 'neblotech.com', 'prfffc.info', 'smarttargetting.net', 'tualipoly.net', 'ytsa.net',
				'aaa.dv0.info', 'adserverplus.com', 'asooda.com', 'cjt1.net', 'easydownloadnow.com', 'grllopa.com', 'lcl2adserver.com', 'negolist.com', 'prickac.com', 'smarttds.ru', 'tubberlo.com', 'yuarth.com',
				'a-ads.com', 'adserverpub.com', 'asrety.com', 'clarityray.com', 'easyflirt-partners.biz', 'groovinads.com', 'ldgateway.com', 'neobux.com', 'primaryads.com', 'smartwebads.com', 'tubemogul.com', 'yuasaghn.com',
				'abbeyblog.me', 'adservhere.com', 'assetize.com', 'clash-media.com', 'easyhits4u.com', 'groupcommerce.com', 'lduhtrp.net', 'neodatagroup.com', 'print3.info', 'smartyads.com', 'tubereplay.com', 'yucce.com',
				'abletomeet.com', 'adservingfactory.com', 'assoc-amazon.ca', 'claxonmedia.com', 'easyinline.com', 'grt02.com', 'leadacceptor.com', 'neoffic.com', 'prizegiveaway.org', 'smileycentral.com', 'tumri.net', 'yumenetworks.com',
				'abnad.net', 'adservinginternational.com', 'assoc-amazon.co.uk', 'clayaim.com', 'easykits.org', 'grt03.com', 'leadad.mobi', 'net3media.com', 'proadsdirect.com', 'smilyes4u.com', 'turbotraff.net', 'yupfiles.net',
				'aboutads.quantcast.com', 'adservpi.com', 'assoc-amazon.com', 'cleafs.com', 'ebannertraffic.com', 'gscontxt.net', 'leadadvert.info', 'net-ad-vantage.com', 'pro-advert.de', 'smowtion.com', 'turn.com', 'yupiromo.ru',
				'absoluteclickscom.com', 'adservr.de', 'assoc-amazon.de', 'clear-request.com', 'ebayobjects.com', 'gscsystemwithdarren.com', 'leadbolt.net', 'netaffiliation.com', 'pro-advertising.com', 'smpgfx.com', 'tusno.com', 'yvoria.com',
				'abtracker.us', 'adsfac.eu', 'assoc-amazon.es', 'clente.com', 'ebayobjects.com.au', 'gsniper2.com', 'leadcola.com', 'netavenir.com', 'probannerswap.com', 'sms-mmm.com', 'tutvp.com', 'yz56lywd.com',
				'accelacomm.com', 'adsfac.net', 'assoc-amazon.fr', 'clevv.com', 'eblastengine.com', 'guardiandigitalcomparison.co.uk', 'leaderpub.fr', 'netflixalternative.net', 'prod.untd.com', 'smutty.com', 'tvas-a.pw', 'yzrnur.com',
				'access-mc.com', 'adsfac.us', 'assoc-amazon.it', 'click.scour.com', 'ebuzzing.com', 'guitaralliance.com', 'leadmediapartners.com', 'netliker.com', 'proffigurufast.com', 'sn00.net', 'tvas-b.pw', 'yzus09by.com',
				'accmgr.com', 'adsfactor.net', 'a-static.com', 'click2jump.com', 'ebz.io', 'gumgum.com', 'leetmedia.com', 'netloader.cc', 'profitpeelers.com', 'snap.com', 'tvprocessing.com', 'z4pick.com',
				'accmndtion.org', 'adsfast.com', 'asterpix.com', 'click4free.info', 'ebzkswbs78.com', 'gunpartners.com', 'legisland.net', 'netpondads.com', 'programresolver.net', 'sndkorea.co.kr', 'twalm.com', 'z5x.net',
				'accounts.pkr.com', 'adsforindians.com', 'astree.be', 'clickable.com', 'edabl.net', 'gururevenue.com', 'lesuard.com', 'netseer.com', 'projectwonderful.com', 'sochr.com', 'tweard.com', 'zangocash.com',
				'accuserveadsystem.com', 'adsfundi.com', 'atemda.com', 'clickad.pl', 'edgeads.org', 'gusufrs.me', 'letsgoshopping.tk', 'netshelter.net', 'pro-market.net', 'socialbirth.com', 'twinpinenetwork.com', 'zanox.com/ppv/',
				'acf-webmaster.net', 'adsfundi.net', 'atmalinks.com', 'clickagy.com', 'edgevertise.com', 'gwallet.com', 'letshareus.com', 'netsolads.com', 'promobenef.com', 'socialelective.com', 'twistads.com', 'zanox-affiliate.de/ppv/',
				'acronym.com', 'adsfuse.com', 'ato.mx', 'clickbet88.com', 'edomz.net', 'gx101.com', 'lfstmedia.com', 'networkplay.in', 'promo-reklama.ru', 'sociallypublish.com', 'twittad.com', 'zaparena.com',
				'actiondesk.com', 'adshack.com', 'atomex.net', 'clickbooth.com', 'eedr.org', 'h12-media.com', 'lgse.com', 'networkxi.com', 'promotionoffer.mobi', 'socialmedia.com', 'twtad.com', 'zappy.co.za',
				'activedancer.com', 'adshexa.com', 'atresadvertising.com', 'clickboothlnk.com', 'effectivemeasure.net', 'halfpriceozarks.com', 'lia-ndr.com', 'networld.hk', 'promotions.sportsbet.com.au', 'socialreach.com', 'tyroo.com', 'zapunited.com',
				'ad.atdmt.com/i/a.html', 'adshopping.com', 'atrinsic.com', 'clickbubbles.net', 'e-find.co', 'halogennetwork.com', 'liftdna.com', 'networldmedia.net', 'promotions-paradise.org', 'socialspark.com', 'u1hw38x0.com', 'zde-engage.com',
				'ad.atdmt.com/i/a.js', 'adshost1.com', 'atwola.com', 'clickcash.com', 'egamingonline.com', 'hanaprop.com', 'ligational.com', 'neudesicmediagroup.com', 'promotiontrack.mobi', 'society6.com', 'u-ad.info', 'zeads.com',
				'ad.yieldpartners.com', 'adshost2.com', 'au2m8.com', 'clickcertain.com', 'e-generator.com', 'hapnr.net', 'ligatus.com', 'newdosug.eu', 'propellerads.com', 'sociocast.com', 'ubudigital.com', 'zedo.com',
				'ad120m.com', 'adshostnet.com', 'auctionnudge.com', 'clickequations.net', 'ekmas.com', 'happilyswitching.net', 'lightad.co.kr', 'newgentraffic.com', 'propellerpops.com', 'sociomantic.com', 'udmserve.net', 'zeesiti.com',
				'ad121m.com', 'adshot.de', 'audience2media.com', 'clickexa.com', 'ektezis.ru', 'harrenmedianetwork.com', 'lightningcast.net', 'newideasdaily.com', 'propelplus.com', 'sodud.com', 'ugaral.com', 'zenoviaexchange.com',
				'ad122m.com', 'adshuffle.com', 'audiencefuel.com', 'clickexperts.net', 'elasticad.net', 'havamedia.net', 'linicom.co.il', 'newsadstream.com', 'prosperent.com', 'so-excited.com', 'ughus.com', 'zenoviagroup.com',
				'ad123m.com', 'adsignals.com', 'audienceprofiler.com', 'clickfuse.com', 'electnext.com', 'havetohave.com', 'linkbuddies.com', 'newsnet.in.ua', 'protally.net', 'soft4dle.com', 'uglyst.com', 'zercstas.com',
				'ad125m.com', 'adsimilis.com', 'auditude.com', 'clickintext.com', 'elefantsearch.com', 'havnr.com', 'linkclicks.com', 'newstogram.com', 'prowlerz.com', 'softonicads.com', 'uiadserver.com', 'zerezas.com',
				'ad127m.com', 'adsinimages.com', 'augmentad.net', 'clickintext.net', 'elepheny.com', 'hb-247.com', 'linkconnector.com', 'newtention.net', 'proximic.com', 'softpopads.com', 'uiqatnpooq.com', 'zferral.com',
				'ad128m.com', 'adskeeper.co.uk', 'aunmdhxrco.com', 'clickkingdom.net', 'elvate.net', 'hdplayer-download.com', 'linkelevator.com', 'nexac.com', 'prre.ru', 'softwares2015.com', 'ukbanners.com', 'zidae.com',
				'ad129m.com', 'adslidango.com', 'auspipe.com', 'clickmngr.com', 'emberads.com', 'hd-plugin.com', 'linkexchange.com', 'nexage.com', 'psclicks.com', 'sokitosa.com', 'unanimis.co.uk', 'ziffdavis.com',
				'ad131m.com', 'adslingers.com', 'auto-im.com', 'clickmyads.info', 'emediate.ch', 'hdvidcodecs.com', 'linkexchangers.net', 'nextmobilecash.com', 'pseqcs05.com', 'solapoka.com', 'underclick.ru', 'zipropyl.com',
				'ad132m.com', 'adslot.com', 'auto-insurance-quotes-compare.com', 'clicknano.com', 'emediate.dk', 'hdvid-codecs-dl.net', 'linkgrand.com', 'ngecity.com', 'ptmzr.com', 'solarmosa.com', 'undertone.com', 'znaptag.com',
				'ad134m.com', 'adsmarket.com', 'automatedtraffic.com', 'clickosmedia.com', 'emediate.eu', 'headup.com', 'linkmads.com', 'nicheadgenerator.com', 'ptp.lolco.net', 'solocpm.com', 'unicast.com', 'zoglafi.info',
				'ad20.net', 'adsmarket.es', 'automateyourlist.com', 'clicks2count.com', 'emediate.se', 'healthaffiliatesnetwork.com', 'linkoffers.net', 'nicheads.com', 'ptp22.com', 'solutionzip.info', 'unitethecows.com', 'zompmedia.com',
				'ad2387.com', 'adsmedia.cc', 'avads.co.uk', 'clicksor.com', 'emjcd.com', 'healthcarestars.com', 'linkreferral.com', 'nighter.club', 'ptp24.com', 'sonnerie.net', 'universityofinternetscience.com', 'zomri.net',
				'ad2adnetwork.biz', 'adsmile.biz', 'avalanchers.com', 'clicksor.net', 'empiremoney.com', 'hebiichigo.com', 'links.io', 'nkredir.com', 'pubdirecte.com', 'sonobi.com', 'unlockr.com', 'zonealta.com',
				'ad2games.com', 'adsmoon.com', 'avazu.net', 'clicksurvey.mobi', 'employers-freshly.org', 'heizuanubr.net', 'linkshowoff.com', 'nmcdn.us', 'pub-fit.com', 'sophiasearch.com', 'unrulymedia.com', 'zonplug.com',
				'ad2up.com', 'adsmws.cloudapp.net', 'avazutracking.net', 'clicksvenue.com', 'emptyspaceads.com', 'helloreverb.com', 'linksmart.com', 'nmwrdr.net', 'pubgears.com', 'sparkstudios.com', 'unterary.com', 'zoomdirect.com.au',
				'ad4game.com', 'adsnative.com', 'avercarto.com', 'clickter.net', 'engineseeker.com', 'hexagram.com', 'linkstorm.net', 'nobleppc.com', 'publicidad.net', 'specificclick.net', 'unuarvse.net', 'zrfrornn.net',
				'ad6media.fr', 'adsnetworkserver.com', 'awaps.net', 'clickthrucash.com', 'enlnks.com', 'hiadone.com', 'linksynergy.com', 'nobsetfinvestor.com', 'publicidees.com', 'specificmedia.com', 'upads.info', 'zugo.com',
				'adacado.com', 'adsnext.net', 'awempire.com', 'clickupto.com', 'enterads.com', 'highcpms.com', 'linkwash.de', 'nonstoppartner.de', 'publicityclerks.com', 'spectato.com', 'updater-checker.net', 'zwaar.org',
				'adaction.se', 'adsniper.ru', 'awin1.com', 'clickwinks.com', 'entrecard.com', 'hijacksystem.com', 'linkworth.com', 'noretia.com', 'publisher.to', 'speeb.com', 'upliftsearch.com', 'zxxds.net',
				'adadvisor.net', 'adsonar.com', 'awltovhc.com', 'clickxchange.com', 'entrecard.s3.amazonaws.com', 'hilltopads.net', 'linkybank.com', 'normkela.com', 'publisheradnetwork.com', 'speedshiftmedia.com', 'uppo.co', 'zypenetwork.com',
				'adagora.com', 'adsopx.com', 'awsclic.com', 'clixgalore.com', 'entru.co', 'h-images.net', 'linkz.net', 'northmay.com', 'pubmatic.com', 'speedsuccess.net', 'urbation.net',
				'adaos-ads.net', 'adsovo.com', 'awsmer.com', 'clixsense.com', 'eosads.com', 'himediads.com', 'liqwid.net', 'nowlooking.net', 'pubmine.com', 'spereminf.com', 'ureace.com',
				'adap.tv', 'adspaper.org', 'awsurveys.com', 'clixtrac.com', 'epicgameads.com', 'himediadx.com', 'lirte.org', 'nowspots.com', 'pubserve.net', 'spiderhood.net', 'urlads.net',
				'adapd.com', 'adspdbl.com', 'axill.com', 'clkads.com', 'e-planning.net', 'hiplair.com', 'listingcafe.com', 'nplexmedia.com', 'pubted.com', 'spinbox.freedom.com', 'urlcash.net',
				'ad-back.net', 'adspeed.com', 'ayboll.com', 'clkmon.com', 'epnredirect.ru', 'hit-now.com', 'liveadexchanger.com', 'npvos.com', 'puhtml.com', 'spinbox.net', 'usbanners.com',
				'ad-balancer.net', 'adspirit.de', 'azads.com', 'clkrev.com', 'eptord.com', 'hits.sys.lv', 'liveadoptimizer.com', 'nquchhfyex.com', 'pulse360.com', 'splazards.com', 'usemax.de',
				'adbard.net', 'ad-sponsor.com', 'azjmp.com', 'clkrev.com^', 'eptum.com', 'hobri.net', 'liveadserver.net', 'nrfort.com', 'pulsemgr.com', 'splinky.com', 'usenetjunction.com',
				'adbasket.net', 'adspring.to', 'azoogleads.com', 'clnk.me', 'eqads.com', 'hokaybo.com', 'livechatflirt.com', 'nrnma.com', 'purpleflag.net', 'splut.com', 'usenetpassport.com',
				'ad-bay.com', 'adspruce.com', 'azorbe.com', 'cloudtracked.com', 'erado.org', 'holidaytravelguide.org', 'livepromotools.com', 'nscontext.com', 'push2check.com', 'spmxs.com', 'usercash.com',
				'adblade.com', 'adspynet.com', 'b117f8da23446a91387efea0e428392a.pl', 'cltomedia.info', 'erendri.com', 'holmgard.link', 'liverail.com', 'nsdsvc.com', 'pxl2015x1.com', 'spoa-soard.com', 'usurv.com',
				'adbma.com', 'adsrevenue.net', 'b6508157d.website', 'clz3.net', 'ergers.net', 'homecareerforyou1.info', 'liversely.net', 'nsmartad.com', 'pxlad.io', 'spongecell.com', 'utarget.co.uk',
				'adboost.com', 'adsring.com', 'babbnrs.com', 'cmfads.com', 'ergerww.net', 'hopfeed.com', 'liveuniversenetwork.com', 'nspmotion.com', 'pzaasocba.com', 'sponsoredby.me', 'utarget.ru',
				'adbooth.net', 'ad-srv.net', 'backbeatmedia.com', 'cmllk1.info', 'ergodob.ru', 'hoppr.co', 'lmebxwbsno.com', 'ntent.com', 'pzuwqncdai.com', 'sponsoredtweets.com', 'utokapa.com',
				'adbrau.com', 'adsrv.us', 'backlinks.com', 'cmllk2.info', 'ero-advertising.com', 'hoptopboy.com', 'lnkgt.com', 'nturveev.com', 'q1media.com', 'sponsormob.com', 'utubeconverter.com',
				'adbrite.com', 'adsrvmedia.com', 'badjocks.com', 'cnt.my', 'eroanalysis.com', 'hornygirlsexposed.com', 'loading-resource.com', 'ntv.io', 'q1mediahydraplatform.com', 'sponsorpalace.com', 'v.fwmrm.net^',
				'adbroo.com', 'adsrvmedia.net', 'baldiro.de', 'cntdy.mobi', 'erovation.com', 'horse-racing-affiliate-program.co.uk', 'localadbuy.com', 'nuaknamg.net', 'q1xyxm89.com', 'sponsorpay.com', 'v.movad.de',
				'adbuddiz.com', 'adsrvr.org', 'bananaflippy.com', 'coadvertise.com', 'erovinmo.com', 'horsered.com', 'localedgemedia.com', 'numberium.com', 'q3sift.com', 'sponsorselect.com', 'v11media.com',
				'adbull.com', 'adssites.net', 'bannerbank.ru', 'coaterhand.net', 'ershgrst.com', 'horyzon-media.com', 'localsearch24.co.uk', 'nuseek.com', 'qadserve.com', 'sportsyndicator.com', 'v2cigs.com',
				'adbureau.net', 'ads-stats.com', 'bannerblasters.com', 'codezap.com', 'escalatenetwork.com', 'hosticanaffiliate.com', 'lockhosts.com', 'nvadn.com', 'qadservice.com', 'spotrails.com', 'v2mlblack.biz',
				'adbutler.com', 'adstatic.com', 'bannerbridge.net', 'codigobarras.net', 'escale.to', 'hotchatdirect.com', 'logo-net.co.uk', 'nvero.net', 'qdmil.com', 'spotscenered.info', 'v8bridge.link',
				'adbuyer.com', 'adsterra.com', 'bannercde.com', 'coedmediagroup.com', 'especifican.com', 'hotelscombined.com', 'loodyas.com', 'nwfhalifax.com', 'qewa33a.com', 'spottt.com', 'vadpay.com',
				'adcade.com', 'ad-stir.com', 'banner-clix.com', 'cogocast.net', 'essayads.com', 'hotelscombined.com.au', 'lookit-quick.com', 'nxtck.com', 'qksrv.net', 'spotxchange.com', 'validclick.com',
				'adcash.com', 'adsummos.net', 'bannerconnect.com', 'cogsdigital.com', 'essaycoupons.com', 'hotfeed.net', 'looksmart.com', 'nyadmcncserve-05y06a.com', 'qksz.net', 'sprintrade.com', 'valuead.com',
				'adcastplus.net', 'adsupermarket.com', 'bannerconnect.net', 'coguan.com', 'esults.net', 'hot-hits.us', 'looneyads.com', 'nymphdate.com', 'qnrzmapdcc.com', 'sproose.com', 'valueaffiliate.net',
				'adcde.com', 'adsupply.com', 'bannerdealer.com', 'coinadvert.net', 'etargetnet.com', 'hotkeys.com', 'looneynetwork.com', 'nzads.net.nz', 'qnsr.com', 'sq2trk2.com', 'valueclick.com',
				'adcdnx.com', 'adsupplyads.com', 'bannerexchange.com.au', 'collection-day.com', 'etgdta.com', 'hotptp.com', 'loopr.co', 'nzphoenix.com', 'qservz.com', 'srtk.net', 'valueclick.net',
				'adcentriconline.com', 'adsurve.com', 'bannerflow.com', 'collective-media.net', 'etmanly.ru', 'hotwords.com', 'lose-ads.de', 'o333o.com', 'quantumads.com', 'srv2trking.com', 'valueclickmedia.com',
				'adcfrthyo.tk', 'adsvert.com', 'bannerflux.com', 'colliersads.com', 'etology.com', 'hotwords.com.br', 'loseads.eu', 'oads.co', 'quensillo.com', 'srv-ad.com', 'valuecommerce.com',
				'adchap.com', 'adswizz.com', 'bannerignition.co.za', 'comclick.com', 'eurew.com', 'hotwords.com.mx', 'losomy.com', 'oainternetservices.com', 'questionmarket.com', 'srvpub.com', 'valuecontent.net',
				'adchemical.com', 'adsxgm.com', 'bannerjammers.com', 'commission.bz', 'euroclick.com', 'hover.in', 'lotteryaffiliates.com', 'obesw.com', 'questus.com', 'srx.com.sg', 'vapedia.com',
				'adchoice.co.za', 'adsymptotic.com', 'bannerlot.com', 'commissionfactory.com.au', 'euromillionairesystem.me', 'hplose.de', 'love-banner.com', 'obeus.com', 'quickcash500.com', 'sta-ads.com', 'vcmedia.com',
				'adclick.lv', 'adtaily.com', 'bannerperformance.net', 'commission-junction.com', 'europacash.com', 'hstpnetwork.com', 'loxtk.com', 'obibanners.com', 'quinstreet.com', 'stackadapt.com', 'vcommission.com',
				'adclick.pk', 'adtaily.eu', 'bannerrage.com', 'commissionlounge.com', 'euros4click.de', 'httpool.com', 'lqcdn.com', 'objects.tremormedia.com', 'qwobl.net', 'stackattacka.com', 'vdopia.com',
				'adclickafrica.com', 'adtaily.pl', 'banner-rotation.com', 'commissionmonster.com', 'e-viral.com', 'httpsecurity.org', 'lqw.me', 'objectservers.com', 'qwzmje9w.com', 'stalesplit.com', 'vectorstock.com',
				'adclickmedia.com', 'adtdp.com', 'bannersmania.com', 'completecarrd.com', 'evolvemediallc.com', 'huzonico.com', 'ltassrv.com.s3.amazonaws.com', 'oceanwebcraft.com', 'qzsccm.com', 'standartads.com', 'vellde.com',
				'ad-clicks.com', 'adtecc.com', 'bannersnack.com', 'compoter.net', 'evolvenation.com', 'hype-ads.com', 'ltassrv.com/goads.swf', 'oclasrv.com', 'r3seek.com', 'star-advertising.com', 'velmedia.net',
				'adcloud.net', 'adtech.de', 'bannersnack.net', 'comscore.com', 'ewebse.com', 'hypeads.org', 'ltassrv.com/serve/', 'oclsasrv.com', 'rabilitan.com', 'stargamesaffiliate.com', 'velti.com',
				'adcolo.com', 'adtechus.com', 'bannersurvey.biz', 'conduit-banners.com', 'exactdrive.com', 'hypemakers.net', 'luadcik.com', 'oclus.com', 'radeant.com', 'starlayer.com', 'vemba.com',
				'adcolony.com', 'adtegrity.net', 'bannertgt.com', 'connatix.com', 'exactly0r.com', 'hyperlinksecure.com', 'lucidmedia.com', 'oehposan.com', 'radicalwealthformula.com', 'startappexchange.com', 'vendexo.com',
				'adconscious.com', 'adteractive.com', 'bannertracker-script.com', 'connectedads.net', 'excellenceads.com', 'hypertrackeraff.com', 'luminate.com', 'offeradvertising.biz', 'radiusmarketing.com', 'startpagea.com', 'veoxa.com',
				'adcount.in', 'adtgs.com', 'bannerweb.com', 'connectionads.com', 'exchange4media.com', 'hypervre.com', 'lushcrush.com', 'offerforge.com', 'raiggy.com', 'statcamp.net', 'versahq.com',
				'adcron.com', 'adtlgc.com', 'baordrid.com', 'connexity.net', 'exciliburn.com', 'hyperwebads.com', 'luxadv.com', 'offerpalads.com', 'rainbowtgx.com', 'statelead.com', 'versetime.com',
				'adcru.com', 'adtoadd.com', 'baronsoffers.com', 'connexplace.com', 'excolobar.com', 'i.skimresources.com', 'luxbetaffiliates.com.au', 'offerserve.com', 'rainwealth.com', 'statsmobi.com', 'vgsgaming-ads.com',
				'addaim.com', 'adtoll.com', 'batarsur.com', 'connextra.com', 'exernala.com', 'iamediaserve.com', 'luxup.ru', 'offersquared.com', 'rampanel.com', 'statstrackeronline.com', 'vhmnetwork.com',
				'addelive.com', 'adtology1.com', 'baungarnr.com', 'construment.com', 'exitexplosion.com', 'iasbetaffiliates.com', 'lx2rv.com', 'ofino.ru', 'raoplenort.biz', 'stealthlockers.com', 'vianadserver.com',
				'ad-delivery.net', 'adtology2.com', 'baypops.com', 'consumergenepool.com', 'exitjunction.com', 'iasrv.com', 'lzjl.com', 'oggifinogi.com', 'rapt.com', 'stepkeydo.com', 'vibrant.co',
				'addiply.com', 'adtology3.com', 'bbelements.com', 'contadd.com', 'exlpor.com', 'ibannerexchange.com', 'm1.fwmrm.net^', 'ohmcasting.com', 'ratari.ru', 'stickyadstv.com', 'vibrantmedia.com',
				'addoer.com', 'adtoma.com', 'beaconads.com', 'contaxe.com', 'exoclick.com', 'ibatom.com', 'm2pub.com', 'oldtiger.net', 'rateaccept.net', 'stocker.bonnint.net', 'video1404.info',
				'addo-mnton.com', 'adtomafusion.com', 'beatchucknorris.com', 'content.ad', 'exponential.com', 'ibryte.com', 'm4pub.com', 'omclick.com', 'rawasy.com', 'streamate.com', 'videoadex.com',
				'addroid.com', 'adtoox.com', 'bebi.com', 'contentabc.com', 'expresswebtraffic.com', 'icdirect.com', 'm57ku6sm.com', 'omg2.com', 'rbnt.org', 'streamdownloadonline.com', 'videoclick.ru',
				'addynamics.eu', 'adtotal.pl', 'becoquin.com', 'contentclick.co.uk', 'extonsuan.com', 'icqadvnew.com', 'm5prod.net', 'omgpm.com', 'rcads.net', 'strikead.com', 'videodeals.com',
				'addynamix.com', 'adtpix.com', 'becoquins.net', 'content-cooperation.com', 'extra33.com', 'idealmedia.com', 'mabirol.com', 'omguk.com', 'rcurn.com', 'struq.com', 'videoegg.com',
				'addynamo.net', 'adtrace.org', 'beead.co.uk', 'contentdigital.info', 'eyere.com', 'identads.com', 'madadsmedia.com', 'omni-ads.com', 'rddywd.com', 'style-eyes.eu', 'videohub.com',
				'adecn.com', 'adtraffic.org', 'beead.net', 'contentjs.com', 'eyereturn.com', 'idownloadgalore.com', 'mad-adz.com', 'onad.eu', 'rdige.com', 'sublimemedia.net', 'videohube.eu',
				'adedy.com', 'adtransfer.net', 'beforescence.com', 'contentolyze.net', 'eyeviewads.com', 'ifilez.org', 'madserving.com', 'onads.com', 'rdsrv.com', 'submitexpress.co.uk', 'videolansoftware.com',
				'adelement.com', 'adtrgt.com', 'begun.ru', 'contentr.net', 'eyewond.hs.llnwd.net', 'iframe.mediaplazza.com', 'madsone.com', 'onclickads.net', 'reachjunction.com', 'successfultogether.co.uk', 'videoliver.com',
				'ademails.com', 'adtrix.com', 'belointeractive.com', 'contenture.com', 'eyewonder.com', 'igameunion.com', 'magicalled.info', 'onedmp.com', 'reachlocal.com', 'suggesttool.com', 'video-loader.com',
				'adengage.com', 'adtrovert.com', 'belvertising.be', 'contentwidgets.net', 'ezadserver.net', 'igloohq.com', 'magnetisemedia.com', 'onenetworkdirect.com', 'reachmode.com', 'suite6ixty6ix.com', 'videologygroup.com',
				'adespresso.com', 'adtruism.com', 'bentdownload.com', 'contexlink.se', 'ezdownloadpro.info', 'ignitioninstaller.com', 'mainadv.com', 'onenetworkdirect.net', 'reactx.com', 'suitesmart.com', 'videoplaza.com',
				'adexcite.com', 'adtwirl.com', 'bepolite.eu', 'c-on-text.com', 'ezmob.com', 'ignup.com', 'mainroll.com', 'onespot.com', 'readserver.net', 'sumarketing.co.uk', 'videoplaza.tv',
				'adexprt.com', 'aduacni.com', 'beringmedia.com', 'contextads.net', 'ezoic.net', 'iiasdomk1m9812m4z3.com', 'makecashtakingsurveys.biz', 'onhitads.net', 'realclick.co.kr', 'sunmedia.net', 'videoplaza.tv/proxy/distributor',
				'adexprts.com', 'adult-adv.com', 'bestcasinopartner.com', 'contextuads.com', 'faggrim.com', 'ilividnewtab.com', 'makemoneymakemoney.net', 'online-adnetwork.com', 'realmatch.com', 'suparewards.com', 'videovfr.com',
				'adextent.com', 'adultadworld.com', 'bestdeals.ws', 'contextweb.com', 'fairadsnetwork.com', 'imasdk.googleapis.com', 'mallsponsor.com', 'onlineadtracker.co.uk', 'realmedia.com', 'super-links.net', 'vidpay.com',
				'adf01.net', 'adultimate.net', 'bestfindsite.com', 'coolerads.com', 'falkag.net', 'imedia.co.il', 'mangoforex.com', 'onlinecareerpackage.com', 'realsecuredredir.com', 'superloofy.com', 'viedeo2k.tv',
				'adfactory88.com', 'adulttds.com', 'bestforexpartners.com', 'coolmirage.com', 'fast2earn.com', 'i-media.co.nz', 'maningrs.com', 'onlinecashmethod.com', 'realsecuredredirect.com', 'supersitetime.com', 'view.atdmt.com',
				'adfarm.mediaplex.com', 'adurr.com', 'bestgameads.com', 'copacet.com', 'fastapi.net', 'imediaaudiences.com', 'marbil24.co.za', 'onlinedl.info', 'realvu.net', 'supplyframe.com', 'viewablemedia.net',
				'ad-feeds.com', 'adv9.net', 'besthitsnow.com', 'coretarget.co.uk', 'fastates.net', 'imediarevenue.com', 'marfeel.com', 'online-media24.de', 'reate.info', 'supremeadsonline.com', 'view-ads.de',
				'adfeedstrk.com', 'adv-adserver.com', 'bestofferdirect.com', 'cor-natty.com', 'fastclick.net', 'imgfeedget.com', 'marketbanker.com', 'onlyalad.net', 'recomendedsite.com', 'surf-bar-traffic.com', 'viewclc.com',
				'ad-flow.com', 'advanseads.com', 'bestonlinecoupons.com', 'cornflip.com', 'fasttracktech.biz', 'img-giganto.net', 'marketfly.net', 'onrampadvertising.com', 'redcourtside.com', 'surveyend.com', 'viewex.co.uk',
				'adfootprints.com', 'advantageglobalmarketing.com', 'bestproducttesters.com', 'coull.com', 'faunsts.me', 'imglt.com', 'markethealth.com', 'onscroll.com', 'redintelligence.net', 'survey-poll.com', 'viewivo.com',
				'adforgames.com', 'advard.com', 'bet3000partners.com', 'coupon2buy.com', 'fbgdc.com', 'imgsniper.com', 'marketingenhanced.com', 'onsitemarketplace.net', 'reduxmediagroup.com', 'surveysforgifts.org', 'viewscout.com',
				'adforgeinc.com', 'advatar.to', 'bet365affiliates.com', 'covertarget.com^*_*.php', 'fb-plus.com', 'imgwebfeed.com', 'marketleverage.com', 'onvertise.com', 'reelcentric.com', 'surveyspaid.com', 'vindicosuite.com',
				'adform.net', 'adventori.com', 'betaffs.com', 'cpabeyond.com', 'fbsvu.com', 'imho.ru', 'marketnetwork.com', 'oodode.com', 'refban.com', 'surveystope.com', 'vipcpms.com',
				'adframesrc.com', 'adversal.com', 'betoga.com', 'cpaclicks.com', 'featuredusers.com', 'imiclk.com', 'marketoring.com', 'ooecyaauiz.com', 'referback.com', 'surveyvalue.mobi', 'vipquesting.com',
				'adfrika.com', 'adversaldisplay.com', 'betrad.com', 'cpaclickz.com', 'featurelink.com', 'imonomy.com', 'marketresearchglobal.com', 'oofte.com', 'regdfh.info', 'surveyvalue.net', 'viralmediatech.com',
				'adfrog.info', 'adversalservers.com', 'bettingpartners.com', 'cpagrip.com', 'feed-ads.com', 'imp*.tradedoubler.com', 'marsads.com', 'oos4l.com', 'regersd.net', 'surveywidget.biz', 'visiads.com',
				'adfrontiers.com', 'adverserve.net', 'bfast.com', 'cpalead.com', 'feljack.com', 'impact-ad.jp', 'martiniadnetwork.com', 'opap.co.kr', 'registry.cw.cm', 'suthome.com', 'visiblegains.com',
				'adfunkyserver.com', 'advertarium.com.ua', 'bh3.net', 'cpalock.com', 'fenixm.com', 'impactradius.com', 'masterads.org', 'openadserving.com', 'regurgical.com', 'svlu.net', 'visiblemeasures.com',
				'adfusion.com', 'advertbox.us', 'biankord.net', 'cpanuk.com', 'f-hookups.com', 'implix.com', 'masternal.com', 'openbook.net', 'rehok.km.ua', 'swadvertising.org', 'visitdetails.com',
				'adgalax.com', 'adverteerdirect.nl', 'biastoful.net', 'cpaway.com', 'fhserve.com', 'impresionesweb.com', 'mastertraffic.cn', 'open-downloads.net', 'reklamz.com', 'swbdds.com', 'visitweb.com',
				'adgardener.com', 'adverticum.net', 'bidgewatr.com', 'cpays.com', 'fidel.to', 'impressionaffiliate.com', 'matiro.com', 'openetray.com', 'relatedweboffers.com', 'swelen.com', 'visualsteel.net',
				'adgatemedia.com', 'advertise.com', 'bidsystem.com', 'cpcadnet.com', 'filestube.com', 'impressionaffiliate.mobi', 'maudau.com', 'opensourceadvertisementnetwork.info', 'relestar.com', 'switchadhub.com', 'vitalads.net',
				'ad-gbn.com', 'advertiseforfree.co.za', 'bidvertiser.com', 'cpfclassifieds.com', 'filetarget.com', 'impressioncontent.info', 'maxserving.com', 'openxadexchange.com', 'relevanti.com', 'swoop.com', 'vivamob.net',
				'adgear.com', 'advertisegame.com', 'biemedia.com', 'c-planet.net', 'filtermomosearch.com', 'impressiondesk.com', 'mb01.com', 'openxenterprise.com', 'relytec.com', 'sxrrxa.net', 'vntsm.com',
				'adgebra.co.in', 'advertisespace.com', 'bigadpoint.net', 'cpm.biz', 'fimserve.com', 'impressionperformance.biz', 'mb102.com', 'openxmarket.asia', 'remiroyal.ro', 'symbiosting.com', 'vogosita.com',
				'adgent007.com', 'advertiseyourgame.com', 'bigfineads.com', 'cpmadvisors.com', 'finalanypar.link', 'impressionvalue.mobi', 'mb104.com', 'operatical.com', 'reporo.net', 'symkashop.ru', 'vogozaw.ru',
				'adgila.com', 'advertising.com', 'bighot.ru', 'cpmaffiliation.com', 'finance-reporting.org', 'in-appadvertising.com', 'mb38.com', 'oplo.org', 'resideral.com', 'syncedvision.com', 'vopdi.com',
				'adgine.net', 'advertising365.com', 'bijscode.com', 'cpmleader.com', 'find-abc.com', 'inbinaryoption.com', 'mb57.com', 'opner.co', 'respecific.net', 'syndicatedsearchresults.com', 'vpico.com',
				'adgitize.com', 'advertising-department.com', 'bimlocal.com', 'cpmmedia.net', 'findbestsolution.net', 'incentaclick.com', 'mbn.com.ua', 'opteama.com', 'respond-adserver.cloudapp.net', 't3q7af0z.com', 'vprmnwbskk.com',
				'adglamour.net', 'advertisingiq.com', 'binaryoptionsgame.com', 'cpmrocket.com', 'find-cheap-hotels.org', 'incomeliberation.com', 'mcdomainalot.com', 'optiad.net', 'respondhq.com', 't3sort.com', 'vs20060817.com',
				'adgorithms.com', 'advertisingpath.net', 'binaryoptionssystems.org', 'cpmstar.com', 'findonlinesurveysforcash.com', 'increase-marketing.com', 'mcdstorage.com', 'optimalroi.info', 'resultlinks.com', 't7row.com', 'vs4entertainment.com',
				'adgoto.com', 'advertisingvalue.info', 'bingo4affiliates.com', 'cpmterra.com', 'findsthat.com', 'indexww.com', 'mdadvertising.net', 'optimatic.com', 'resultsz.com', 'tacastas.com', 'vs4family.com',
				'adgroups.com', 'advertjunction.com', 'binlayer.com', 'cpmtree.com', 'firaxtech.com', 'indiabanner.com', 'mdialog.com', 'optimizeadvert.biz', 'retargeter.com', 'tacoda.net', 'vsservers.net',
				'adgrx.com', 'advertlead.net', 'binlayer.de', 'cpuim.com', 'firefeeder.com', 'indiads.com', 'mdn2015x1.com', 'optinemailpro.com', 'retkow.com', 'tacticalrepublic.com', 'vth05dse.com',
				'adhese.be', 'advertlets.com', 'bin-layer.de', 'cpulaptop.com', 'firegob.com', 'indianbannerexchange.com', 'mdn2015x2.com', 'opt-intelligence.com', 'reussissonsensemble.fr', 'tafmaster.com', 'vuiads.de',
				'adhese.com', 'advertmarketing.com', 'bin-layer.ru', 'cpvads.com', 'firmharborlinked.com', 'indianlinkexchange.com', 'mdn2015x4.com', 'opt-n.net', 'rev2pub.com', 'taggify.net', 'vuiads.info',
				'adhese.net', 'advertmedias.com', 'bitads.net', 'cpvadvertise.com', 'firstadsolution.com', 'indianweeklynews.com', 'meadigital.com', 'orangeads.fr', 'revcontent.com', 'tagjunction.com', 'vuiads.net',
				'adhitzads.com', 'advertpay.net', 'bitcoinadvertisers.com', 'cpvmarketplace.info', 'firstclass-download.com', 'indicate.to', 'media.net', 'orarala.com', 'revenue.com', 'tagshost.com', 'vungle.com',
				'adhood.com', 'advertrev.com', 'bitfalcon.tv', 'cpvtgt.com', 'firstimpression.io', 'indieclick.com', 'media303.com', 'orbengine.com', 'revenuegiants.com', 'tailsweep.com', 'w00tads.com',
				'adhostingsolutions.com', 'advertserve.com', 'bittads.com', 'cpx24.com', 'firstlightera.com', 'indofad.com', 'media6degrees.com', 'oskale.ru', 'revenuehits.com', 'takensparks.com', 'w00tmedia.net',
				'adhub.co.nz', 'advertstatic.com', 'bitx.tv', 'cpxadroit.com', 'firstmediahub.com', 'industrybrains.com', 'media970.com', 'ospreymedialp.com', 'revenuemantra.com', 'talaropa.com', 'w3exit.com',
				'adicate.com', 'advertstream.com', 'bizographics.com', 'cpxinteractive.com', 'first-rate.com', 'inentasky.com', 'mediaadserver.org', 'othersonline.com', 'revenuemax.de', 'tangozebra.com', 'w4.com',
				'adigniter.org', 'advertur.ru', 'bizrotator.com', 'crakmedia.com', 'fisari.com', 'inetinteractive.com', 'media-app.com', 'ourunlimitedleads.com', 'revfusion.net', 'tapad.com', 'w4statistics.info',
				'adikteev.com', 'advertxi.com', 'bizzclick.com', 'crazyad.net', 'fixionmedia.com', 'infectiousmedia.com', 'mediaclick.com', 'oveld.com', 'revmob.com', 'tapjoyads.com', 'w5statistics.info',
				'adimise.com', 'advg.jp', 'blamads.com', 'crazylead.com', 'fl-ads.com', 'infinite-ads.com', 'mediacpm.com', 'overhaps.com', 'revokinets.com', 'tardangro.com', 'w9statistics.info',
				'adimpact.com', 'advgoogle.com', 'blamcity.com', 'crazyvideosempire.com', 'flagads.net', 'infinityads.com', 'mediaffiliation.com', 'overture.com', 'revresda.com', 'targetadverts.com', 'waddr.com',
				'adimperia.com', 'ad-vice.biz', 'blardenso.com', 'creative-serving.com', 'flashclicks.com', 'influads.com', 'mediaflire.com', 'overturs.com', 'revresponse.com', 'targetnet.com', 'wafmedia5.com',
				'adimpression.net', 'adviva.net', 'blazwuatr.com', 'creditcards15x.tk', 'flashtalking.com', 'info4.a7.org', 'mediaforge.com', 'oxado.com', 'revsci.net', 'targetpoint.com', 'waframedia3.com',
				'adimps.com', 'advmd.com', 'blinkadr.com', 'crhikay.me', 'flaudnrs.me', 'infolinks.com', 'mediag4.com', 'oxsng.com', 'rewardisement.com', 'targetspot.com', 'wagershare.com',
				'adinch.com', 'advmedialtd.com', 'blinko.es', 'crispads.com', 'flaurse.net', 'information-sale.com', 'media-general.com', 'oxtracking.com', 'rewardsaffiliates.com', 'tattomedia.com', 'wahoha.com',
				'adincon.com', 'advombat.ru', 'blinkogold.es', 'criteo.com', 'fliionos.co.uk', 'infra-ad.com', 'mediagridwork.com', 'oxybe.com', 'rewardstyle.com', 'tbaffiliate.com', 'wamnetwork.com',
				'ad-indicator.com', 'advpoints.com', 'blipi.net', 'criteo.net', 'flite.com', 'inktad.com', 'mediakeywords.com', 'ozertesa.com', 'rfihub.net', 'tcadops.ca', 'wangfenxi.com',
				'adindigo.com', 'advrtice.com', 'blockthis.es', 'crossrider.com', 'fllwert.net', 'inmobi.com', 'media-ks.net', 'ozonemedia.com', 'rgadvert.com', 'td553.com', 'wapdollar.in',
				'adinfinity.com.au', 'advsnx.net', 'blogads.com', 'crowdgatheradnetwork.com', 'flodonas.com', 'innity.com', 'medialand.ru', 'p2ads.com', 'rhgersf.com', 'teads.tv', 'waptrick.com',
				'adinterax.com', 'advuatianf.com', 'blogbannerexchange.com', 'crowdgravity.com', 'fluidads.co', 'innity.net', 'medialation.net', 'p7vortex.com', 'rhown.com', 'teambetaffiliates.com', 'warezlayer.to',
				'adip.ly', 'adwhirl.com', 'blogclans.com', 'cruiseworldinc.com', 'fluxads.com', 'innovid.com', 'media-networks.ru', 'paads.dk', 'rhythmxchange.com', 'teasernet.com', 'warfacco.com',
				'adiqglobal.com', 'adwired.mobi', 'bloggerex.com', 'ctasnet.com', 'flyertown.ca', 'insightexpress.com', 'mediaonenetwork.net', 'padsdelivery.com', 'ricead.com', 'techclicks.net', 'watchfree.flv.in',
				'adiquity.com', 'adwires.com', 'blogherads.com', 'ctm-media.com', 'flymyads.com', 'insightexpressai.com', 'mediaonpro.com', 'padstm.com', 'richmedia247.com', 'technicssurveys.info', 'wateristian.com',
				'adireland.com', 'adwordsservicapi.com', 'blogohertz.com', 'ctrhub.com', 'fmdwbsfxf0.com', 'insitepromotion.com', 'mediapeo.com', 'p-advg.com', 'richwebmedia.com', 'technoratimedia.com', 'waymp.com',
				'adisfy.com', 'adworkmedia.com', 'blogscash.info', 'cubics.com', 'fmpub.net', 'insitesystems.com', 'mediaseeding.com', 'pagefair.net', 'rikhov.ru', 'telemetryverification.net', 'wbptqzmv.com',
				'adisn.com', 'adworldmedia.com', 'bluazard.net', 'cuelinks.com', 'fmsads.com', 'inskinad.com', 'media-servers.net', 'pagesinxt.com', 'ringtonematcher.com', 'teosredic.com', 'wbsadsdel.com',
				'adition.com', 'adworldmedia.net', 'blueadvertise.com', 'curancience.com', 'focalex.com', 'inskinmedia.com', 'mediatarget.com', 'paid4ad.de', 'ringtonepartner.com', 'teracent.net', 'wbsadsdel2.com',
				'aditor.com', 'adxcore.com', 'bluestreak.com', 'currentlyobsessed.me', 'focre.info', 'insta-cash.net', 'mediative.ca', 'paidonresults.net', 'ripplead.com', 'teracreative.com', 'wcmcs.net',
				'adjal.com', 'adxion.com', 'blumi.to', 'curtisfrierson.com', 'foodieblogroll.com', 'instantbannercreator.com', 'mediatraffic.com', 'paidsearchexperts.com', 'riverbanksand.com', 'terraclicks.com', 'wcpanalytics.com',
				'adjector.com', 'adxpose.com', 'bmanpn.com', 'cybmas.com', 'foonad.com', 'instantdollarz.com', 'mediatraks.com', 'pakbanners.com', 'rixaka.com', 'testfilter.com', 'weareheard.org',
				'adjug.com', 'adxpower.com', 'bnetworx.com', 'cygnus.com', 'footar.com', 'instantpaydaynetwork.com', 'medleyads.com', 'panachetech.com', 'rlex.org', 'testnet.nl', 'webads.co.nz',
				'adjuggler.com', 'adyoulike.com', 'bnhtml.com', 'd.adroll.com', 'footerslideupad.com', 'instinctiveads.com', 'medrx.sensis.com.au', 'pantherads.com', 'rmxads.com', 'text-link-ads.com', 'webads.nl',
				'adjuggler.net', 'adyoz.com', 'bnmla.com', 'd.m3.net', 'footnote.com', 'instivate.com', 'medyanet.net', 'paperg.com', 'rnmd.net', 'textonlyads.com', 'web-adservice.com',
				'adjungle.com', 'adz.co.zw', 'bnr.sys.lv', 'd03x2011.com', 'forced-lose.de', 'integral-marketing.com', 'medyanetads.com', 'paradocs.ru', 'robocat.me', 'textsrv.com', 'webadvertise123.com',
				'adk2.co', 'adzerk.net', 'bogads.com', 'd1110e4.se', 'forex-affiliate.com', 'intellibanners.com', 'meendocash.com', 'partner.googleadservices.com', 'rocketier.net', 'tfag.de', 'webgains.com',
				'adk2.com', 'adzhub.com', 'bongacams.com', 'd2ship.com', 'forex-affiliate.net', 'intellitxt.com', 'meetgoodgirls.com', 'partner.video.syndication.msn.com', 'rogueaffiliatesystem.com', 'tgtmedia.com', 'webmedia.co.il',
				'adk2.net', 'adzmob.com', 'bonusfapturbo.com', 'd3lens.com', 'forexyard.com', 'intenthq.com', 'meetic-partners.com', 'partner-ads.com', 'roicharger.com', 'th4wwe.net', 'weborama.fr',
				'adk2x.com', 'adzonk.com', 'bonzuna.com', 'da-ads.com', 'forifiha.com', 'intentmedia.net', 'meetsexygirls.org', 'partnerearning.com', 'roirocket.com', 'theadgateway.com', 'websearchers.net',
				'adkengage.com', 'adzouk.com', 'boo-box.com', 'dadegid.ru', 'forpyke.com', 'interactivespot.net', 'megacpm.com', 'partnermax.de', 'romance-net.com', 'theads.me', 'webseeds.com',
				'adkick.net', 'adzs.nl', 'booklandonline.info', 'danitabedtick.net', 'forrestersurveys.com', 'interclick.com', 'megapopads.com', 'partycasino.com', 'ronetu.ru', 'thebannerexchange.com', 'webtrackerplus.com',
				'adklip.com', 'afcyhf.com', 'boostclic.com', 'dapper.net', 'foulsomty.com', 'interestably.com', 'megbase.com', 'partypartners.com', 'rotaban.ru', 'thebflix.info', 'webtraffic.ttinet.com',
				'adknowledge.com', 'afdads.com', 'bormoni.ru', 'darwarvid.com', 'fowar.net', 'interesting.cc', 'meinlist.com', 'partypills.org', 'rotatingad.com', 'the-consumer-reporter.org', 'webusersurvey.com',
				'adkonekt.com', 'aff.biz', 'bororas.com', 'das5ku9q.com', 'f-questionnaire.com', 'intermarkets.net', 'mellowads.com', 'partypoker.com', 'rotorads.com', 'theequalground.info', 'wegetpaid.net',
				'adlayer.net', 'affbot1.com', 'boydadvertising.co.uk', 'dashboardad.net', 'frameptp.com', 'internetadbrokers.com', 'menepe.com', 'pas-rahav.com', 'roulettebotplus.com', 'thelistassassin.com', 'wegotmedia.com',
				'adlegend.com', 'affbot3.com', 'boylesportsreklame.com', 'data.adroll.com', 'freebannerswap.co.uk', 'interpolls.com', 'mentad.com', 'passionfruitads.com', 'rovion.com', 'theloungenet.com', 'weliketofuckstrangers.com',
				'adlink.net', 'affbot7.com', 'bptracking.com', 'dating-banners.com', 'freebiesurveys.com', 'interworksmedia.co.kr', 'mentalks.ru', 'pautaspr.com', 'roxyaffiliates.com', 'themidnightmatulas.com', 'wensdteuy.com',
				'adlinx.info', 'affbot8.com', 'br.rk.com', 'datinggold.com', 'freecouponbiz.com', 'intextdirect.com', 'merchenta.com', 'pay-click.ru', 'rtbidder.net', 'thepiratereactor.net', 'werbe-sponsor.de',
				'adlisher.com', 'affbuzzads.com', 'brainient.com', 'datumreact.com', 'freedownloadsoft.net', 'intextscript.com', 'mercuras.com', 'paydotcom.com', 'rtbmedia.org', 'thepornsurvey.com', 'wfnetwork.com',
				'adloaded.com', 'affec.tv', 'branchr.com', 'dbbsrv.com', 'freepaidsurveyz.com', 'intextual.net', 'messagespaceads.com', 'payperpost.com', 'rtbpop.com', 'therewardsurvey.com', 'wgreatdream.com',
				'adlooxtracking.com', 'affiliate.com', 'brand.net', 'dbclix.com', 'freerotator.com', 'intgr.net', 'metaffiliation.com', 'pc-ads.com', 'rtbpops.com', 'thewebgemnetwork.com', 'wh5kb0u4.com',
				'adlure.biz', 'affiliate.cx', 'brandads.net', 'dealcurrent.com', 'freeskreen.com', 'intopicmedia.com', 'metavertising.com', 'p-comme-performance.com', 'rterdf.me', 'thewheelof.com', 'where.com',
				'adlure.net', 'affiliate-b.com', 'brandaffinity.net', 'decisionmark.com', 'freesoftwarelive.com', 'inttrax.com', 'metavertizer.com', 'pdfcomplete.com', 'rubiconproject.com', 'thiscdn.com', 'whoads.net',
				'adlux.com', 'affiliatebannerfarm.com', 'brandclik.com', 'decisionnews.com', 'fresh8.co', 'intuneads.com', 'metodoroleta24h.com', 'p-digital-server.com', 'rubikon6.if.ua', 'thoseads.com', 'whtsrv9.com',
				'ad-m.asia', 'affiliateedge.com', 'brand-display.com', 'decknetwork.net', 'friendlyduck.com', 'inuvo.com', 'metrics.io', 'pe2k2dty.com', 'rugistoto.net', 'thoughtleadr.com', 'why-outsource.net',
				'adm.fwmrm.net/p/mtvn_live/', 'affiliateer.com', 'brandreachsys.com', 'dedicatedmedia.com', 'frtya.com', 'inuxu.co.in', 'meviodisplayads.com', 'peakclick.com', 'rummyaffiliates.com', 'thoughtsondance.info', 'widget.yavli.com',
				'admagnet.net', 'affiliatefuel.com', 'braside.ru', 'dedicatednetworks.com', 'fruitkings.com', 'investingchannel.com', 'meya41w7.com', 'peelawaymaker.com', 'runadtag.com', 'thrilamd.net', 'widgetadvertising.biz',
				'admailtiser.com', 'affiliatefuture.com', 'bravenetmedianetwork.com', 'deepmetrix.com', 'frxle.com', 'inviziads.com', 'mezimedia.com', 'peemee.com', 'rwpads.com', 'tidaltv.com', 'widgetbanner.mobi',
				'admamba.com', 'affiliate-gate.com', 'breadpro.com', 'defaultimg.com', 'frxrydv.com', 'ip-adress.com', 'mgcash.com', 'peer39.net', 'ryminos.com', 'tightexact.net', 'widgetbucks.com',
				'adman.gr', 'affiliategateways.co', 'brealtime.com', 'deguiste.com', 'ftjcfx.com', 'ipredictive.com', 'mgcashgate.com', 'penuma.com', 's.adroll.com', 'tinbuadserv.com', 'widgetlead.net',
				'admanage.com', 'affiliategroove.com', 'bridgetrack.com', 'dehtale.ru', 'ftv-publicite.fr', 'ipromote.com', 'mgplatform.com', 'pepperjamnetwork.com', 's2d6.com', 'tisadama.com', 'widgets.fccinteractive.com',
				'admarketplace.net', 'affiliatelounge.com', 'brighteroption.com', 'delivery45.com', 'fuandarst.com', 'isohits.com', 'mibebu.com', 'percularity.com', 'sa.entireweb.com', 'tiser.com', 'widgetsurvey.biz',
				'ad-maven.com', 'affiliatemembership.com', 'brightshare.com', 'delivery47.com', 'fulltraffic.net', 'isparkmedia.com', 'microad.jp', 'perfb.com', 'safeadnetworkdata.net', 'tissage-extension.com', 'widgetvalue.net',
				'admaxim.com', 'affiliate-robot.com', 'broadstreetads.com', 'delivery49.com', 'funklicks.com', 'itrengia.com', 'microadinc.com', 'perfcreatives.com', 'safecllc.com', 'tjoomo.com', 'widgetwidget.mobi',
				'admaya.in', 'affiliatesensor.com', 'brucelead.com', 'delivery51.com', 'fusionads.net', 'iu16wmye.com', 'microsoftaffiliates.net', 'perfoormapp.info', 'safelistextreme.com', 'tkqlhce.com', 'wigetmedia.com'}

	local _,_,reqURL = string.find(hc.request_header, '[gG]ET *([^;\r\n]+) HTTP/')
	for i, white in ipairs(whitelist) do
		if not re.match(reqURL, white) then
			for i, black in ipairs(blacklist) do
				if re.match(reqURL, black) then
					local function set_var(x, y)
						_G[x] = y
					end
					set_var('for_saving', 'no')
					set_var('clear', 'yes')
					local data = MY_EXTENSION_DATA[hc.monitor_index]
					table.insert(data.monitor_string_array, {priority=1, text='Blocked by Ad-Block'})
					set_color({153, 0, 0}, 1)
					hc.answer_header='HTTP/1.1 200 OK\r\n'..
					'Server: System\r\n'..
					'Content-Type: text/html\r\n'..
					'Pragma: no-cache\r\n'..
					'Cache-control: no-cache, must-revalidate, no-store\r\n'..
					'Connection: close\r\n\r\n'
					hc.answer_body ='<html>\r\n'..
					'\r\n'..
					'<body>\r\n'..
					'Dear user!<br><br>\r\n'..
					'Site: '..reqURL..'<br>is blocked.<br><br>\r\n'..
					'Blocked word: '..black..'<br><br><br>\r\n'..
					'Contact to your ISP administrator.\r\n'..
					'\r\n'..
					'</body>\r\n'..
					'</html>'
					hc.action = 'stop'
				end
			end
		end
	end
end